// src/components/ui/AnimatedCounter.vue
<template>
  <span ref="el" class="count-animate">{{ display }}</span>
</template>

<script setup>
import { ref, watch } from "vue";
import { useReveal } from "@/composables/useReveal";

const props = defineProps({
  value: { type: String, required: true },
});

const display = ref(props.value);
const { el, visible } = useReveal({ threshold: 0.3 });

watch(visible, (v) => {
  if (!v) return;

  const prefersReduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  if (prefersReduced) return;

  const match = props.value.match(/^(\[?)([X-YZ\d]+)(\]?\+?)$/);
  if (!match || match[1] === "[" || props.value.includes("[")) return;

  const num = parseInt(match[2], 10);
  const suffix = props.value.replace(/[\d]/g, "");
  if (isNaN(num)) return;

  const duration = 1200;
  const start = performance.now();

  function tick(now) {
    const progress = Math.min((now - start) / duration, 1);
    const eased = 1 - Math.pow(1 - progress, 3);
    display.value = Math.round(num * eased) + suffix;
    if (progress < 1) requestAnimationFrame(tick);
  }

  display.value = "0" + suffix;
  requestAnimationFrame(tick);
});
</script>

// montessori-institute/src/components/ui/AnimatedCounter.tsx
import { useEffect, useState } from "react";

type Props = {
  value: string;
  active: boolean;
};

/** Parses numeric prefix from placeholder strings like "[X]+" or "[X]" */
function parseValue(raw: string): { num: number; prefix: string; suffix: string } | null {
  const match = raw.match(/^(\[?)(\d+(?:\.\d+)?)(\]?)(.*)$/);
  if (!match) return null;
  return {
    prefix: match[1] === "[" ? "[" : "",
    suffix: (match[3] === "]" ? "]" : "") + match[4],
    num: parseFloat(match[2]),
  };
}

export function AnimatedCounter({ value, active }: Props) {
  const parsed = parseValue(value.replace(/\[X\]/g, "0"));
  const [display, setDisplay] = useState(value);

  useEffect(() => {
    if (!active || !parsed || value.includes("[X]")) {
      setDisplay(value);
      return;
    }
    const start = performance.now();
    const tick = (now: number) => {
      const p = Math.min((now - start) / 1200, 1);
      const eased = 1 - Math.pow(1 - p, 3);
      setDisplay(`${parsed.prefix}${Math.round(parsed.num * eased)}${parsed.suffix}`);
      if (p < 1) requestAnimationFrame(tick);
    };
    requestAnimationFrame(tick);
  }, [active, value, parsed]);

  return <span>{display}</span>;
}
